/**
 * Decision Outcome Attestation V1 — TS builder parity + refuse attestation.
 *
 * Proves:
 *   - the TS leaf is BYTE-EXACT with the Python implementation via golden
 *     vectors generated by twzrd_agent_intel.decision_attestation (fixtures/
 *     decision-outcome-vectors.json) — settled, blocked_never_signed (with
 *     synthetic-marker payer sha256 fallback), and a minimal vector,
 *   - the Python test key's Ed25519 signature over the leaf verifies here
 *     (same wire form the Python verifier consumes: base58 sig + pubkey),
 *   - buildBlockedNeverSignedAttestation turns a BLOCK DecisionToken into a
 *     signed refuse artifact bound to the refused intentHash, verifiable
 *     against the operator's published decision key,
 *   - contract violations throw (settled without anchor, block with anchor,
 *     non-BLOCK token, tampered leaf fails signature check).
 *
 * Run: npx tsx test/outcome-attestation.test.ts
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  createLocalDecisionSigner,
  signDecision,
} from "../src/decision-token.js";
import { intentHash, type PaymentIntent } from "../src/intent.js";
import {
  buildBlockedNeverSignedAttestation,
  computeDecisionOutcomeLeafV1,
  verifyOutcomeAttestationSignature,
  type DecisionOutcomeFields,
} from "../src/outcome-attestation.js";

const here = dirname(fileURLToPath(import.meta.url));
const vectors = JSON.parse(
  readFileSync(join(here, "fixtures", "decision-outcome-vectors.json"), "utf8"),
);

/* 1. Golden-vector parity: every Python leaf recomputes byte-exact in TS */
for (const v of vectors.vectors) {
  const p = v.preimage;
  const fields: DecisionOutcomeFields = {
    decisionId: p.decision_id,
    counterparty: p.counterparty,
    verdict: p.verdict,
    outcome: p.outcome,
    timestampUnix: p.timestamp_unix,
    intentHash: p.intent_hash,
    payer: p.payer,
    settlementTx: p.settlement_tx,
    preflightId: p.preflight_id,
  };
  const leaf = "0x" + computeDecisionOutcomeLeafV1(fields).toString("hex");
  assert.equal(leaf, v.leaf, `leaf parity failed for vector ${v.name}`);
}

/* 2. Python signature verifies in TS (cross-language authenticity wire form) */
for (const v of vectors.vectors) {
  if (!v.signature_b58) continue;
  assert.equal(
    verifyOutcomeAttestationSignature(
      { leaf: v.leaf, signature: v.signature_b58 },
      vectors.signing_pubkey_b58,
    ),
    true,
    `python signature must verify for vector ${v.name}`,
  );
  // Tampered leaf -> same signature must fail.
  const flipped = v.leaf.slice(0, -1) + (v.leaf.endsWith("0") ? "1" : "0");
  assert.equal(
    verifyOutcomeAttestationSignature(
      { leaf: flipped, signature: v.signature_b58 },
      vectors.signing_pubkey_b58,
    ),
    false,
  );
}

/* 3. Refuse artifact: BLOCK token -> signed blocked_never_signed attestation */
{
  const signer = createLocalDecisionSigner();
  const intent: PaymentIntent = {
    protocol: "x402",
    network: "solana",
    asset: "USDC",
    amount: "1.00",
    payTo: "WashSe11erWa11etXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    resource: { url: "https://evil.example.com/paid" },
  };
  const token = await signDecision(
    {
      decision: "block",
      reasonCodes: ["WASH_FLAGGED"],
      intentHash: intentHash(intent),
      policyVersion: "twzrd-pc-v1",
      decisionId: "dec-refuse-1",
      expiresAt: new Date(Date.now() + 60_000).toISOString(),
    },
    signer,
  );
  const att = await buildBlockedNeverSignedAttestation(token, {
    counterparty: intent.payTo,
    signer,
    timestampUnix: 1_760_000_200,
  });
  assert.equal(att.signed, true);
  assert.equal(att.preimage.outcome, "blocked_never_signed");
  assert.equal(att.preimage.decision_id, token.decisionId);
  assert.equal(att.preimage.intent_hash, token.intentHash);
  assert.equal(att.preimage.settlement_anchor, null);
  assert.match(att.leaf, /^0x[0-9a-f]{64}$/);
  assert.ok(att.signing_pubkey, "local signer publishes its pubkey");
  // Verifies against the operator's published key...
  assert.equal(
    verifyOutcomeAttestationSignature(att, att.signing_pubkey!),
    true,
  );
  // ...and NOT against someone else's key.
  const other = createLocalDecisionSigner();
  const otherAtt = await buildBlockedNeverSignedAttestation(token, {
    counterparty: intent.payTo,
    signer: other,
    timestampUnix: 1_760_000_200,
  });
  assert.equal(verifyOutcomeAttestationSignature(att, otherAtt.signing_pubkey!), false);

  // Non-BLOCK tokens are rejected.
  const allowToken = await signDecision(
    { ...token, decision: "allow" as const, decisionId: "dec-allow" },
    signer,
  );
  await assert.rejects(
    buildBlockedNeverSignedAttestation(allowToken, {
      counterparty: intent.payTo,
      signer,
    }),
    /requires a BLOCK token/,
  );
}

/* 4. Structural contract throws (fail closed at build) */
{
  const base: DecisionOutcomeFields = {
    decisionId: "d",
    counterparty: "c",
    verdict: "allow",
    outcome: "settled",
    timestampUnix: 1,
    payer: "11111111111111111111111111111112",
    settlementTx: "5".repeat(88),
  };
  assert.throws(
    () => computeDecisionOutcomeLeafV1({ ...base, settlementTx: null }),
    /requires a settlement anchor/,
  );
  assert.throws(
    () => computeDecisionOutcomeLeafV1({ ...base, verdict: "block" }),
    /gate breach/,
  );
  assert.throws(
    () =>
      computeDecisionOutcomeLeafV1({
        ...base,
        verdict: "block",
        outcome: "blocked_never_signed",
      }),
    /must NOT carry a settlement anchor/,
  );
  assert.throws(
    () => computeDecisionOutcomeLeafV1({ ...base, decisionId: "" }),
    /non-empty/,
  );
  assert.throws(
    () => computeDecisionOutcomeLeafV1({ ...base, intentHash: "tiv1:zz" }),
    /64 hex/,
  );
}

/* 5. Block-proof v1.2: verified transcript -> attached signed refuse */
{
  const {
    attachBlockOutcomeAttestation,
    AUTOGATE_BLOCK_PROOF_SCHEMA_V1_2,
    buildAutogateBlockProof,
  } = await import("../src/block-proof.js");
  const signer = createLocalDecisionSigner();
  const proof = buildAutogateBlockProof({
    run_id: "run-refuse-42",
    target_seller: "WashSe11erWa11etXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    aborted: true,
    internal_reason: "twzrd_wash_flagged",
    decision: "block",
    wash_flagged: true,
    signer_invocations: 0,
    actual_spend_usdc: 0,
    onchain_settlements: 0,
    execution_mode: "harness",
  });
  assert.equal(proof.verified, true);
  const upgraded = await attachBlockOutcomeAttestation(proof, {
    signer,
    timestampUnix: 1_760_000_300,
  });
  assert.equal(upgraded.schema_version, AUTOGATE_BLOCK_PROOF_SCHEMA_V1_2);
  const att2 = upgraded.outcome_attestation!;
  assert.equal(att2.preimage.decision_id, "run-refuse-42");
  assert.equal(att2.preimage.counterparty, proof.target_seller);
  assert.equal(att2.preimage.outcome, "blocked_never_signed");
  assert.equal(att2.preimage.intent_hash, null); // no token -> no fabricated bind
  // Leaf recomputes from the carried preimage and the signature verifies.
  const recomputed =
    "0x" +
    computeDecisionOutcomeLeafV1({
      decisionId: att2.preimage.decision_id,
      counterparty: att2.preimage.counterparty,
      verdict: att2.preimage.verdict,
      outcome: att2.preimage.outcome,
      timestampUnix: att2.preimage.timestamp_unix,
      intentHash: att2.preimage.intent_hash,
      payer: att2.preimage.payer,
      settlementTx: att2.preimage.settlement_tx,
      preflightId: att2.preimage.preflight_id,
    }).toString("hex");
  assert.equal(recomputed, att2.leaf);
  assert.equal(verifyOutcomeAttestationSignature(att2, att2.signing_pubkey!), true);
  // Input proof is not mutated.
  assert.equal(proof.outcome_attestation, undefined);

  // Unverified transcript (signer was invoked) -> refuse to sign the claim.
  const dirty = buildAutogateBlockProof({
    run_id: "run-dirty",
    target_seller: proof.target_seller,
    aborted: true,
    internal_reason: "twzrd_wash_flagged",
    signer_invocations: 1,
  });
  assert.equal(dirty.verified, false);
  await assert.rejects(
    attachBlockOutcomeAttestation(dirty, { signer }),
    /requires a VERIFIED block proof/,
  );
}

console.log("outcome-attestation.test.ts: ALL PASSED");
